### ISSUE TITLE
Code review for Nuvola Player project

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvola-app-soundcloud#2]
Hello @kixam, thanks for your work. There are some issues that needs to be fixed before it can become an officially supported script.

* [x] Remove file `description.html`.
* [x] Replace icon in `src` directory with a generic icon set from [the template](https://github.com/tiliado/nuvola-app-template/archive/master.tar.gz) and update `Makefile` as well. Alexander King will provide a proper icon later.
* [x] Add your copyright info to the top of `integrate.js`
* [x] Update copyright information in `README.md` (see template for reference) and include necessary license files from the template.
* [x] Set `version_minor`  in `metadata.json` back to `0`. See a recently added  [rule about releases](https://tiliado.github.io/nuvolaplayer/development/apps/guidelines.html#releases).
* [x] Could it be possible to set a proper `allowed_uri` regular expression, e.g. `^https?://(www\.)?soundcloud\.com/.*`?
* [x] `integrate.js:26: * TODO: Love song action.` Consider [creating a ticket](https://github.com/tiliado/nuvola-app-soundcloud/issues/new) for this task.
* [x] `integrate.js:59-65: WebApp._onInitAppRunner = function(emitter)` Check `document.readyState` as in [service integrations tutorial](https://tiliado.github.io/nuvolaplayer/development/apps/tutorial.html#create-integration-script)

**Comment by kixam** [comment]
Hello @fenryxo ,

I think I did everything you asked. Please know that `integrate.js:26: * TODO: Love song action.` was actually a private reminder that I forgot to remove before committing, but the functionality has been there for some time.

**Comment by fenryxo** [comment]
Thanks @kixam. There are new issues:

* [ ] `README.md` doesn't contain complete copyright information for `integrate.js`: Add `Copyright 2014 David Šabata <his@email>`, license MIT. Find his e-mail address.
* [ ] Add your e-mail to the copyright info. Copyright holders must be reached by e-mail.
* [ ] Please replace your icon with a generic icon set from [the template](https://github.com/tiliado/nuvola-app-template/archive/master.tar.gz). The orange color is really inconsistent with other icons. Alexander King will create a proper symbolic icon.

**Comment by kixam** [comment]
Hello @fenryxo

All done. I will be unavailable for a week so I hope this is it for now.

**Comment by fenryxo** [comment]
Great, @kixam. I've released version 1.1, published packages and announced your script. Welcome aboard. Next steps are:

* [ ] Subscribe to [the nuvola-player-devel mailing list]() to be notified about important changes. Don't be afraid of spam, it's a low volume list.
* [ ] [Create a Tiliado account](https://tiliado.eu/accounts/signup/) and post your username here. I'll add you to the Tiliado developers group. You can then log in in Nuvola Player to disable donate bar. Also, if you use Debian/Ubuntu/Fedora, you'll have access to Nuvola Player 3.1 Rolling Releases.

**Comment by kixam** [comment]
done and done

**Comment by fenryxo** [comment]
Great @kixam. I've just added you to the Tiliado developers group.
