### ISSUE TITLE
Crash on click "Preferences"

### ISSUE THREAD

**Issue by DakEnviy** [tiliado/nuvola-app-soundcloud#9]
I just clicked on button "Preferences", and Soundcloud web app window has been closed.

**Comment by fenryxo** [comment]
Hello @DakEnviy. Thanks for taking the time to report your issue. I need more information to investigate it further. Could you provide me with more details as specified in [Bug reporting guidelines](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#basic-information)? Thanks.

**Comment by fenryxo** [comment]
No response from the reporter, closing.
